use_frameworks!

platform :ios, '8.0'

target 'LJViewController_Example' do
  pod 'LJViewController', :path => '../'

  target 'LJViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
